### ISSUE TITLE
Orion performance for most viewed / followed queries

### ISSUE THREAD

**Issue by wyrdrender** [Joystream/orion#19]
Turns out new Orion version isn't working very well on production. With the production data (we currently have 37k events there) and running mostViewedVideos in the last 7 days takes 2.5s to compute. For last 30 days it's 24s

**Comment by kdembler** [comment]
I have an idea for one possible solution, feel free to come up with something different:

Instead of allowing for an arbitrary `period` (we should likely change that to `timePeriod`), we could predefine allowed time ranges. Let's say that's "forever", 30d and 7d. Then for each of those we could keep a couple of variables in memory:
- `timePeriodEvents` - list of all events in this time period
- `timePeriodViews` - map of views in this time period
- anything else we'd want to, like `timePeriodChannelViews`, `timePeriodCategoryViews` etc

When a new event is added, it gets pushed to `timePeriodEvents` of all the supported time periods. Also, appropriate counters are incremented for each time period (video view, category, channel etc). That means that the events list and the counters may be out-of-sync just after the events is added.

Then, when user requests info about some specific time period (let's assume they want most viewed videos over the last 7d), we do the following:
1. We clean up the associated events list. So we basically iterate from beginning and find events that no longer match the desired period. This will happen quite rarely, as most of the time the list should be up to date.
2. For each event that was removed, we decrement appropriate counters for this time period
3. Once that cleanup is done, we're left with correct mapping for views and give those to the user

With this approach 1+2 will happen only sometimes and will do very little computing. So most of the time only 3 will get executed which has trivial complexity as it's only a read from an object.

Let me know what you think about that. Also, if anything is unclear, please ask and I will try to provide a better explanation

**Comment by wyrdrender** [comment]
I don't think I have anything to add. Before I read this I came up with a similar solution, so let's go with that. If anything comes up during implementation, I will consult it with you.
