### ISSUE TITLE
Missing notifications!!!

### ISSUE THREAD

**Issue by bedeho** [Joystream/orion#318]
I don't believe the NFT notifications are working properly, there was a bid that outbid me, but I received no notfication on email or in app, despite both being enabled in settings
![Screenshot 2024-03-14 at 18 38 48](https://github.com/Joystream/orion/assets/437292/0eaa955e-2f0c-493a-84ce-3425ca0778c5)

Please also review if the CRT notifications really work also.

**Comment by zeeshanakram3** [comment]
>  there was a bid that outbid me, but I received no notfication on email or in app, despite both being enabled in settings

I just checked the implementation and currently, no notifications are dispatched if someone outbids you in `OpenAuction` (since technically in the open auction your bid is still valid if a bid outbids you, and the NFT owner might still accept your bid despite having a higher offer)

It's just an implementation detail, but do let me know if we want to have notifications for Open Auction outbids.
